export const SAMPLE_PRODUCTS = [
  {
    id: "1",
    name: "Pure Turmeric Powder",
    description: "100% natural turmeric sourced from the finest farms. Rich in curcumin with earthy aroma.",
    price: 149,
    original_price: 199,
    image_url: "https://images.unsplash.com/photo-1615485500704-8e990f9900f7?w=400&q=80",
    category_slug: "ground-spices",
    category: "Ground Spices",
    in_stock: true,
    stock_quantity: 150,
    is_featured: true,
    is_bestseller: true,
    tags: ["organic", "bestseller"],
    rating: 4.8,
    reviews: 234,
  },
  {
    id: "2",
    name: "Whole Black Pepper",
    description: "Premium whole black pepper with intense aroma and bold flavor. Farm-fresh quality.",
    price: 189,
    original_price: 249,
    image_url: "https://images.unsplash.com/photo-1599909631844-09b7fca23fe5?w=400&q=80",
    category_slug: "whole-spices",
    category: "Whole Spices",
    in_stock: true,
    stock_quantity: 200,
    is_featured: false,
    is_bestseller: true,
    tags: ["premium"],
    rating: 4.7,
    reviews: 189,
  },
  {
    id: "3",
    name: "Garam Masala Blend",
    description: "Classic North Indian spice blend. Perfect for curries, biryanis, and gravies.",
    price: 199,
    original_price: 279,
    image_url: "https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=400&q=80",
    category_slug: "masala-blends",
    category: "Masala Blends",
    in_stock: true,
    stock_quantity: 120,
    is_featured: true,
    is_bestseller: true,
    tags: ["bestseller", "popular"],
    rating: 4.9,
    reviews: 412,
  },
  {
    id: "4",
    name: "Red Chilli Powder",
    description: "Bold and fiery red chilli powder. Adds vibrant color and heat to any dish.",
    price: 129,
    original_price: 179,
    image_url: "https://images.unsplash.com/photo-1583119022894-919a68a3d0e3?w=400&q=80",
    category_slug: "ground-spices",
    category: "Ground Spices",
    in_stock: true,
    stock_quantity: 300,
    is_featured: false,
    is_bestseller: false,
    tags: ["hot", "popular"],
    rating: 4.6,
    reviews: 167,
  },
  {
    id: "5",
    name: "Coriander Powder",
    description: "Freshly ground coriander seeds with a mild, citrusy fragrance. Essential kitchen staple.",
    price: 99,
    original_price: 139,
    image_url: "https://images.unsplash.com/photo-1602147777226-ef5e3b7c3834?w=400&q=80",
    category_slug: "ground-spices",
    category: "Ground Spices",
    in_stock: true,
    stock_quantity: 250,
    is_featured: false,
    is_bestseller: false,
    tags: ["essential"],
    rating: 4.5,
    reviews: 98,
  },
  {
    id: "6",
    name: "Cumin Seeds",
    description: "Aromatic whole cumin seeds. Perfect for tempering, tadka, and spice blends.",
    price: 159,
    original_price: 219,
    image_url: "https://images.unsplash.com/photo-1546548970-71785318a17b?w=400&q=80",
    category_slug: "whole-spices",
    category: "Whole Spices",
    in_stock: true,
    stock_quantity: 180,
    is_featured: false,
    is_bestseller: false,
    tags: ["aromatic"],
    rating: 4.7,
    reviews: 143,
  },
  {
    id: "7",
    name: "Mustard Oil (Cold Pressed)",
    description: "Pure cold-pressed mustard oil. Rich in omega-3 and natural antioxidants.",
    price: 349,
    original_price: 449,
    image_url: "https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=400&q=80",
    category_slug: "oils",
    category: "Oils",
    in_stock: true,
    stock_quantity: 90,
    is_featured: true,
    is_bestseller: false,
    tags: ["cold-pressed", "premium"],
    rating: 4.8,
    reviews: 211,
  },
  {
    id: "8",
    name: "Basmati Rice (Premium)",
    description: "Long-grain aged Basmati rice with natural fragrance. Ideal for biryani and pulao.",
    price: 599,
    original_price: 749,
    image_url: "https://images.unsplash.com/photo-1586201375761-83865001e31c?w=400&q=80",
    category_slug: "rice",
    category: "Rice",
    in_stock: true,
    stock_quantity: 75,
    is_featured: true,
    is_bestseller: true,
    tags: ["premium", "aged"],
    rating: 4.9,
    reviews: 328,
  },
  {
    id: "9",
    name: "Chana Dal (Split Chickpeas)",
    description: "High-protein split chickpeas. Nutritious and versatile — great for dal and snacks.",
    price: 189,
    original_price: 229,
    image_url: "https://images.unsplash.com/photo-1509440159596-0249088772ff?w=400&q=80",
    category_slug: "pulses",
    category: "Pulses",
    in_stock: true,
    stock_quantity: 160,
    is_featured: false,
    is_bestseller: false,
    tags: ["protein", "healthy"],
    rating: 4.6,
    reviews: 76,
  },
  {
    id: "10",
    name: "Whole Wheat Atta (Stone Ground)",
    description: "Traditional stone-ground whole wheat atta. Retains natural nutrients and bran.",
    price: 299,
    original_price: 379,
    image_url: "https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?w=400&q=80",
    category_slug: "atta-flour",
    category: "Atta & Flour",
    in_stock: true,
    stock_quantity: 110,
    is_featured: false,
    is_bestseller: false,
    tags: ["stone-ground", "healthy"],
    rating: 4.7,
    reviews: 154,
  },
  {
    id: "11",
    name: "Cardamom (Green Elaichi)",
    description: "Premium green cardamom pods with intense aroma. Perfect for sweets, chai, and biryanis.",
    price: 449,
    original_price: 599,
    image_url: "https://images.unsplash.com/photo-1608613304899-ea8098577e38?w=400&q=80",
    category_slug: "whole-spices",
    category: "Whole Spices",
    in_stock: true,
    stock_quantity: 60,
    is_featured: true,
    is_bestseller: true,
    tags: ["premium", "aromatic"],
    rating: 4.9,
    reviews: 289,
  },
  {
    id: "12",
    name: "Spice Starter Combo Pack",
    description: "5-spice starter kit: Turmeric, Chilli, Coriander, Cumin & Garam Masala. Perfect gift.",
    price: 499,
    original_price: 699,
    image_url: "https://images.unsplash.com/photo-1603134872573-c99ec13c6db1?w=400&q=80",
    category_slug: "combo-packs",
    category: "Combo Packs",
    in_stock: true,
    stock_quantity: 45,
    is_featured: true,
    is_bestseller: true,
    tags: ["combo", "gift", "bestseller"],
    rating: 4.9,
    reviews: 445,
  },
];
